### ISSUE TITLE
load_experiment.js not retrieving "[SUB_TOTALTIME_SUB]"

### ISSUE THREAD

**Issue by jkredz** [expfactory/expfactory-battery#45]
The experimentDraw() function doesnt seem to return a list of the experiments.  I suspect that since the code is not properly retrieving the value from SUB_TOTALTIME_SUB because of the "" on line 16.
 
var time = time || "[SUB_TOTALTIME_SUB]"

Also where is load_experiment.js retrieving values from 
 [SUB_EXPERIMENTCONCAT_SUB]
[SUB_EXPERIMENTTIMES_SUB]?

**Comment by vsoch** [comment]
You should run the experiments using the command line tool, expfactory --run, which will fill in those values for you.

**Comment by vsoch** [comment]
try updating the expfactory command line executable, those variables should be filled in with the latest version.

**Comment by jkredz** [comment]
Updating expfactory worked out.  I guess its not possible to use older versions of expfactory since using the browser battery generator always pulls from the github repo.
