### ISSUE TITLE
expfactory fails after installing psiturk

### ISSUE THREAD

**Issue by oricon** [expfactory/expfactory-battery#67]
I installed and set-up psiturk (using pip install psiturk, pip installed with conda) and now expfactory won't open. Even after I `pip uninstall psiturk` I get the below error when calling expfactory. Further, even if I uninstall and reinstall expfactory, the error remains. The only solution I've found is to complete remove and reinstall anaconda python. Is this a anaconda issue or an expfactory/psiturk issue.

psyc308-01:~ congalab$ expfactory
Traceback (most recent call last):
  File "/opt/anaconda/anaconda2/bin/expfactory", line 11, in <module>
    load_entry_point('expfactory==2.5.46', 'console_scripts', 'expfactory')()
  File "/opt/anaconda/anaconda2/lib/python2.7/site-packages/expfactory/scripts.py", line 141, in main
    from expfactory.interface import start
  File "/opt/anaconda/anaconda2/lib/python2.7/site-packages/expfactory/interface.py", line 44, in <module>
    app = EFServer(__name__)
  File "/opt/anaconda/anaconda2/lib/python2.7/site-packages/expfactory/interface.py", line 23, in __init__
    custom_battery_download(tmpdir=self.tmpdir)
  File "/opt/anaconda/anaconda2/lib/python2.7/site-packages/expfactory/vm.py", line 37, in custom_battery_download
    download_repo(repo,"%s/%s/" %(tmpdir,repo))
  File "/opt/anaconda/anaconda2/lib/python2.7/site-packages/expfactory/vm.py", line 23, in download_repo
    return Repo.clone_from("https://github.com/expfactory/expfactory-%s" %(repo_type), destination)
AttributeError: type object 'Repo' has no attribute 'clone_from'

**Comment by vsoch** [comment]
hey @oricon ! This looks like a version error with the github module in Python, which likely was updated / changed when you updated psiturk. Could you verify the version? The one that I have that should work is `2.1.1`.  Here is how you check:

     ipython
     from git import Repo
     Repo. [TAB][TAB] to see if there is a function clone_from

To check your version:

      import git
      git.__version__

To fix the version:

     pip install gitpython==2.1.1

And it's my fault for not specifying the version in requirements.txt, and also my fault for having you need to think about dependencies, period!  u I wasn't super experienced with containers when I designed the client, and a much better approach would have all dependencies tightly packaged to avoid these issues.

**Comment by oricon** [comment]
Thanks! That helped. I had git 2.11.1 installed originally, so I
uninstalled that and installed 2.1.1. I then installed psiturk and it looks
like psiturk changed git to 0.1.7. But after installing 2.1.1 both psiturk
and expfactory worked.

-Joe

--
Joseph M. Orr, Ph.D.
Assistant Professor
Department of Psychology &
Texas A&M Institute for Neuroscience
Texas A&M University
College Station, TX

**Comment by vsoch** [comment]
no problem! I'm going to close the issue, please ping if you have any more trouble.
